spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:tcp://localhost/~/developer/database/springMiniProject
#    url: jdbc:h2:~/developer/database/springMiniProject
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create
      use-new-id-generator-mappings: false

    properties:
      hibernate:
        show_sql: true
        format_sql: true

  thymeleaf:
    cache: false

  mvc:
    path match:
      matching-strategy: ant_path_matcher

logging.level:
  org.hibernate.SQL: debug
#  org.hibernate.type: trace

server:
  port: 9090
